//Ext.defineModel("Ems.baseinfo.WorkUnit",{
Ext.define("Ems.baseinfo.WorkUnit",{
	extend:"Ext.data.Model",
	idProperty:'id',
	fields:[
		{name:'id',type:'string'},
		{name:'memo',type:'string'},
		{name:'name',type:'string'},
		{name:'status',type:'bool'},
		{name:'loginName',type:'string'},
		{name:'password',type:'string'}
	],
	associations:[
	]
});