Ext.defineModel("Leon.desktop.role.RoleFunAssociation",{
	extend:"Ext.data.Model",
	fields:[
		{name:'id',type:'string'},
		{name:'text',type:'string'},//role的名称
		{name:'roleId',type:'string'},
		{name:'funId',type:'string'},
		{name:'permissionType',type:'string'}
	]
});