Ext.defineModel("Leon.desktop.role.RoleRole",{
	extend:"Ext.data.Model",
	fields:[
		{name:'id',type:'string'},
		{name:'roleRoleEnum',type:'string'},//role的名称
		{name:'createDate',type:'date'},
		{name:'current_id',type:'string'},
		{name:'other_id',type:'string'}	
	],
	associations:[
		{type:'belongsTo',model:'Leon.desktop.role.Role',associatedName:'Current'},
		{type:'belongsTo',model:'Leon.desktop.role.Role',associatedName:'Other'}
	]
});