Ext.defineModel("Leon.desktop.org.OrgType",{
	extend:"Ext.data.Model",
	idProperty:'id',
	fields:[
		{name:'id',type:'string'},
		{name:'iconCls',type:'string'},
		{name:'name',type:'string'}
	],
	associations:[
	]
});