Ext.defineModel("Ems.install.InstallOutType",{
	extend:"Ext.data.Model",
	idProperty:'id',
	fields:[
		{name:'id',type:'string'},
		{name:'memo',type:'string'},
		{name:'name',type:'string'}
	],
	associations:[
	]
});