Ext.defineModel("Ems.adjust.AdjustList",{
	extend:"Ext.data.Model",
	idProperty:'id',
	fields:[
		{name:'id',type:'string'},
		{name:'adjust_id',type:'string'},
		{name:'ecode',type:'string'},
		{name:'in_num',type:'int'},
		{name:'out_num',type:'int'},
		{name:'status',type:'bool'},
		
		{name:'brand_name',type:'string'},
		{name:'prod_name',type:'string'},
		{name:'prod_spec',type:'string'},
		{name:'subtype_name',type:'string'},
		{name:'supplier_name',type:'string'},
		{name:'equipment_style',type:'string'},
		{name:'equipment_status',type:'int'}
	],
	associations:[
	]
});