Ext.define("Leon.desktop.menu.Menu",{
	extend:"Ext.data.Model",
	fields:[
		{name:'id',type:'auto'},
		{name:'code',type:'string'},
		{name:'text',type:'string'},
		{name:'pluginUrl',type:'string'},
		{name:'scripts',type:'string'},
		{name:'iconCls',type:'string'},
		{name:'reportCode',type:'string'},
		{name:'url',type:'string'}//是从功能里面来的
	]
});
