Ext.defineModel("Leon.desktop.parameter.Parameter",{
	extend:"Ext.data.Model",
	fields:[
		{name:'id',type:'auto'},
		{name:'name',type:'string'},
		{name:'desc',type:'string'},
		{name:'showModel',type:'string'},
		{name:'showModelName',type:'string'},
		{name:'valueEnum',type:'string'},
		{name:'valueEnumName',type:'string'},
		{name:'content',type:'string'},
		{name:'subjects',type:'string'},
		{name:'subjectNames',type:'string'},
		{name:'sort',type:'int'},//引用的次数
		{name:'vaidation',type:'string'}
	]	
});
